sudo: true
language: scala
scala:
  - 2.10.4
jdk:
  - openjdk7
  - oraclejdk8
before_install: # workaround taken from https://github.com/travis-ci/travis-ci/issues/5227
  - cat /etc/hosts # optionally check the content *before*
  - sudo hostname "$(hostname | cut -c1-63)"
  - sed -e "s/^\\(127\\.0\\.0\\.1.*\\)/\\1 $(hostname | cut -c1-63)/" /etc/hosts | sudo tee /etc/hosts
  - cat /etc/hosts # optionally check the content *after*
