java -Dconfig.file=word-deid.conf -Drepeats=1 -jar main.jar < deid_t1_v2_unlabeled.txt > data/deid_t1_v2_mr-w-r1.txt
java -Dconfig.file=word-deid.conf -Drepeats=2 -jar main.jar < deid_t1_v2_unlabeled.txt > data/deid_t1_v2_mr-w-r2.txt
java -Dconfig.file=word-deid.conf -Drepeats=3 -jar main.jar < deid_t1_v2_unlabeled.txt > data/deid_t1_v2_mr-w-r3.txt
java -Dconfig.file=word-deid.conf -Drepeats=4 -jar main.jar < deid_t1_v2_unlabeled.txt > data/deid_t1_v2_mr-w-r4.txt
java -Dconfig.file=word-deid.conf -Drepeats=5 -jar main.jar < deid_t1_v2_unlabeled.txt > data/deid_t1_v2_mr-w-r5.txt
java -Dconfig.file=word-deid.conf -Drepeats=6 -jar main.jar < deid_t1_v2_unlabeled.txt > data/deid_t1_v2_mr-w-r6.txt
java -Dconfig.file=word-deid.conf -Drepeats=7 -jar main.jar < deid_t1_v2_unlabeled.txt > data/deid_t1_v2_mr-w-r7.txt
java -Dconfig.file=word-deid.conf -Drepeats=8 -jar main.jar < deid_t1_v2_unlabeled.txt > data/deid_t1_v2_mr-w-r8.txt
java -Dconfig.file=word-deid.conf -Drepeats=9 -jar main.jar < deid_t1_v2_unlabeled.txt > data/deid_t1_v2_mr-w-r9.txt
java -Dconfig.file=word-deid.conf -Drepeats=10 -jar main.jar < deid_t1_v2_unlabeled.txt > data/deid_t1_v2_mr-w-r10.txt
java -Dconfig.file=word-deid.conf -Drepeats=11 -jar main.jar < deid_t1_v2_unlabeled.txt > data/deid_t1_v2_mr-w-r11.txt
java -Dconfig.file=word-deid.conf -Drepeats=12 -jar main.jar < deid_t1_v2_unlabeled.txt > data/deid_t1_v2_mr-w-r12.txt
java -Dconfig.file=word-deid.conf -Drepeats=13 -jar main.jar < deid_t1_v2_unlabeled.txt > data/deid_t1_v2_mr-w-r13.txt
java -Dconfig.file=word-deid.conf -Drepeats=14 -jar main.jar < deid_t1_v2_unlabeled.txt > data/deid_t1_v2_mr-w-r14.txt
java -Dconfig.file=word-deid.conf -Drepeats=15 -jar main.jar < deid_t1_v2_unlabeled.txt > data/deid_t1_v2_mr-w-r15.txt
java -Dconfig.file=word-deid.conf -Drepeats=16 -jar main.jar < deid_t1_v2_unlabeled.txt > data/deid_t1_v2_mr-w-r16.txt
java -Dconfig.file=word-deid.conf -Drepeats=17 -jar main.jar < deid_t1_v2_unlabeled.txt > data/deid_t1_v2_mr-w-r17.txt
java -Dconfig.file=word-deid.conf -Drepeats=18 -jar main.jar < deid_t1_v2_unlabeled.txt > data/deid_t1_v2_mr-w-r18.txt
